# The Docker image that will be used to build your app
image: stateoftheartio/qt6:6.6-wasm-aqt
# Functions that should be executed before the build script is run
before_script:
  - echo $PATH
  - source emsdk_env.sh
  - emsdk activate latest
pages:
  script:
    - mkdir build
    - mkdir public
    - qt-cmake ./ -B ./build -G Ninja
    - cmake --build ./build
    - cp build/appPowerPoint2.html public/

  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
