# The Docker image that will be used to build your app
image: stateoftheartio/qt6:6.6-wasm-aqt
# Functions that should be executed before the build script is run
before_script:
  - source emsdk.env
pages:
  script:
    - mkdir build
    - cd build
    - cmake ..
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
