# The Docker image that will be used to build your app
image: alteved2v/qt-wasm-aqt
# Functions that should be executed before the build script is run
before_script:
  - source emsdk_env.sh
pages:
  script:
    - mkdir build
    - mkdir public
    - qt-cmake ./ -B ./build -G Ninja
    - cmake --build ./build
    # Should exist better way to do this
    - cp build/appPowerPoint2.js build/appPowerPoint2.wasm build/qtloader.js build/qtlogo.svg public/
    - cp build/appPowerPoint2.html public/index.html

  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
